[package]
name = "mockio"
version = "0.1.0"
authors = ["sourcebusters"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "*"
serde = "*"
log = "*"
